// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CSMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use CSMessage.newBuilder() to construct.
    private CSMessage() {
      initFields();
    }
    private CSMessage(boolean noInit) {}
    
    private static final CSMessage defaultInstance;
    public static CSMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.LoginCheckAccountRequest loginCheckAccountRequest = 1;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.LoginCreateRoleRequest loginCreateRoleRequest = 2;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.LoginGetRoleDataRequest loginGetRoleDataRequest = 3;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightClientReadyRequest fightClientReadyRequest = 4;
    public static final int FIGHTCLIENTREADYREQUEST_FIELD_NUMBER = 4;
    private boolean hasFightClientReadyRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest fightClientReadyRequest_;
    public boolean hasFightClientReadyRequest() { return hasFightClientReadyRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest getFightClientReadyRequest() { return fightClientReadyRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightLoadResourceCompleteRequest fightLoadResourceCompleteRequest = 5;
    public static final int FIGHTLOADRESOURCECOMPLETEREQUEST_FIELD_NUMBER = 5;
    private boolean hasFightLoadResourceCompleteRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest fightLoadResourceCompleteRequest_;
    public boolean hasFightLoadResourceCompleteRequest() { return hasFightLoadResourceCompleteRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest getFightLoadResourceCompleteRequest() { return fightLoadResourceCompleteRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightGameActionRequest fightGameActionRequest = 6;
    public static final int FIGHTGAMEACTIONREQUEST_FIELD_NUMBER = 6;
    private boolean hasFightGameActionRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest fightGameActionRequest_;
    public boolean hasFightGameActionRequest() { return hasFightGameActionRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest getFightGameActionRequest() { return fightGameActionRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightGameOverRequest fightGameOverRequest = 7;
    public static final int FIGHTGAMEOVERREQUEST_FIELD_NUMBER = 7;
    private boolean hasFightGameOverRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest fightGameOverRequest_;
    public boolean hasFightGameOverRequest() { return hasFightGameOverRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest getFightGameOverRequest() { return fightGameOverRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightReadFrameRequest fightReadFrameRequest = 8;
    public static final int FIGHTREADFRAMEREQUEST_FIELD_NUMBER = 8;
    private boolean hasFightReadFrameRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest fightReadFrameRequest_;
    public boolean hasFightReadFrameRequest() { return hasFightReadFrameRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest getFightReadFrameRequest() { return fightReadFrameRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightGetGameAwardRequest fightGetGameAwardRequest = 17;
    public static final int FIGHTGETGAMEAWARDREQUEST_FIELD_NUMBER = 17;
    private boolean hasFightGetGameAwardRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest fightGetGameAwardRequest_;
    public boolean hasFightGetGameAwardRequest() { return hasFightGetGameAwardRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest getFightGetGameAwardRequest() { return fightGetGameAwardRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PillageRoleRequest pillageRoleRequest = 9;
    public static final int PILLAGEROLEREQUEST_FIELD_NUMBER = 9;
    private boolean hasPillageRoleRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest pillageRoleRequest_;
    public boolean hasPillageRoleRequest() { return hasPillageRoleRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest getPillageRoleRequest() { return pillageRoleRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PillageCancelRequest pillageCancelRequest = 10;
    public static final int PILLAGECANCELREQUEST_FIELD_NUMBER = 10;
    private boolean hasPillageCancelRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest pillageCancelRequest_;
    public boolean hasPillageCancelRequest() { return hasPillageCancelRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest getPillageCancelRequest() { return pillageCancelRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PillageShowRequest pillageShowRequest = 11;
    public static final int PILLAGESHOWREQUEST_FIELD_NUMBER = 11;
    private boolean hasPillageShowRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest pillageShowRequest_;
    public boolean hasPillageShowRequest() { return hasPillageShowRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest getPillageShowRequest() { return pillageShowRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardGetCardsInfoRequest cardGetCardsInfoRequest = 12;
    public static final int CARDGETCARDSINFOREQUEST_FIELD_NUMBER = 12;
    private boolean hasCardGetCardsInfoRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest cardGetCardsInfoRequest_;
    public boolean hasCardGetCardsInfoRequest() { return hasCardGetCardsInfoRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest getCardGetCardsInfoRequest() { return cardGetCardsInfoRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardEditCardListRequest cardEditCardListRequest = 13;
    public static final int CARDEDITCARDLISTREQUEST_FIELD_NUMBER = 13;
    private boolean hasCardEditCardListRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest cardEditCardListRequest_;
    public boolean hasCardEditCardListRequest() { return hasCardEditCardListRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest getCardEditCardListRequest() { return cardEditCardListRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardLvUpRequest cardLvUpRequest = 14;
    public static final int CARDLVUPREQUEST_FIELD_NUMBER = 14;
    private boolean hasCardLvUpRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest cardLvUpRequest_;
    public boolean hasCardLvUpRequest() { return hasCardLvUpRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest getCardLvUpRequest() { return cardLvUpRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardChooseUseCardListRequest cardChooseUseCardListRequest = 15;
    public static final int CARDCHOOSEUSECARDLISTREQUEST_FIELD_NUMBER = 15;
    private boolean hasCardChooseUseCardListRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest cardChooseUseCardListRequest_;
    public boolean hasCardChooseUseCardListRequest() { return hasCardChooseUseCardListRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest getCardChooseUseCardListRequest() { return cardChooseUseCardListRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardChangeMainCardRequest cardChangeMainCardRequest = 18;
    public static final int CARDCHANGEMAINCARDREQUEST_FIELD_NUMBER = 18;
    private boolean hasCardChangeMainCardRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest cardChangeMainCardRequest_;
    public boolean hasCardChangeMainCardRequest() { return hasCardChangeMainCardRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest getCardChangeMainCardRequest() { return cardChangeMainCardRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PingRequest pingRequest = 16;
    public static final int PINGREQUEST_FIELD_NUMBER = 16;
    private boolean hasPingRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest pingRequest_;
    public boolean hasPingRequest() { return hasPingRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest getPingRequest() { return pingRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.GMRejectLoginRequest gmRejectLoginRequest = 19;
    public static final int GMREJECTLOGINREQUEST_FIELD_NUMBER = 19;
    private boolean hasGmRejectLoginRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest gmRejectLoginRequest_;
    public boolean hasGmRejectLoginRequest() { return hasGmRejectLoginRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest getGmRejectLoginRequest() { return gmRejectLoginRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.GMTerminatedServerRequest gmTerminatedServerRequest = 20;
    public static final int GMTERMINATEDSERVERREQUEST_FIELD_NUMBER = 20;
    private boolean hasGmTerminatedServerRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest gmTerminatedServerRequest_;
    public boolean hasGmTerminatedServerRequest() { return hasGmTerminatedServerRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest getGmTerminatedServerRequest() { return gmTerminatedServerRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.GMOpenLoginRequest gmOpenLoginRequest = 21;
    public static final int GMOPENLOGINREQUEST_FIELD_NUMBER = 21;
    private boolean hasGmOpenLoginRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest gmOpenLoginRequest_;
    public boolean hasGmOpenLoginRequest() { return hasGmOpenLoginRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest getGmOpenLoginRequest() { return gmOpenLoginRequest_; }
    
    private void initFields() {
      loginCheckAccountRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      fightClientReadyRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.getDefaultInstance();
      fightLoadResourceCompleteRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.getDefaultInstance();
      fightGameActionRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.getDefaultInstance();
      fightGameOverRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.getDefaultInstance();
      fightReadFrameRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.getDefaultInstance();
      fightGetGameAwardRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.getDefaultInstance();
      pillageRoleRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.getDefaultInstance();
      pillageCancelRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.getDefaultInstance();
      pillageShowRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.getDefaultInstance();
      cardGetCardsInfoRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.getDefaultInstance();
      cardEditCardListRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.getDefaultInstance();
      cardLvUpRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.getDefaultInstance();
      cardChooseUseCardListRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.getDefaultInstance();
      cardChangeMainCardRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.getDefaultInstance();
      pingRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.getDefaultInstance();
      gmRejectLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.getDefaultInstance();
      gmTerminatedServerRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.getDefaultInstance();
      gmOpenLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(3, getLoginGetRoleDataRequest());
      }
      if (hasFightClientReadyRequest()) {
        output.writeMessage(4, getFightClientReadyRequest());
      }
      if (hasFightLoadResourceCompleteRequest()) {
        output.writeMessage(5, getFightLoadResourceCompleteRequest());
      }
      if (hasFightGameActionRequest()) {
        output.writeMessage(6, getFightGameActionRequest());
      }
      if (hasFightGameOverRequest()) {
        output.writeMessage(7, getFightGameOverRequest());
      }
      if (hasFightReadFrameRequest()) {
        output.writeMessage(8, getFightReadFrameRequest());
      }
      if (hasPillageRoleRequest()) {
        output.writeMessage(9, getPillageRoleRequest());
      }
      if (hasPillageCancelRequest()) {
        output.writeMessage(10, getPillageCancelRequest());
      }
      if (hasPillageShowRequest()) {
        output.writeMessage(11, getPillageShowRequest());
      }
      if (hasCardGetCardsInfoRequest()) {
        output.writeMessage(12, getCardGetCardsInfoRequest());
      }
      if (hasCardEditCardListRequest()) {
        output.writeMessage(13, getCardEditCardListRequest());
      }
      if (hasCardLvUpRequest()) {
        output.writeMessage(14, getCardLvUpRequest());
      }
      if (hasCardChooseUseCardListRequest()) {
        output.writeMessage(15, getCardChooseUseCardListRequest());
      }
      if (hasPingRequest()) {
        output.writeMessage(16, getPingRequest());
      }
      if (hasFightGetGameAwardRequest()) {
        output.writeMessage(17, getFightGetGameAwardRequest());
      }
      if (hasCardChangeMainCardRequest()) {
        output.writeMessage(18, getCardChangeMainCardRequest());
      }
      if (hasGmRejectLoginRequest()) {
        output.writeMessage(19, getGmRejectLoginRequest());
      }
      if (hasGmTerminatedServerRequest()) {
        output.writeMessage(20, getGmTerminatedServerRequest());
      }
      if (hasGmOpenLoginRequest()) {
        output.writeMessage(21, getGmOpenLoginRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataRequest());
      }
      if (hasFightClientReadyRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getFightClientReadyRequest());
      }
      if (hasFightLoadResourceCompleteRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getFightLoadResourceCompleteRequest());
      }
      if (hasFightGameActionRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getFightGameActionRequest());
      }
      if (hasFightGameOverRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getFightGameOverRequest());
      }
      if (hasFightReadFrameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getFightReadFrameRequest());
      }
      if (hasPillageRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getPillageRoleRequest());
      }
      if (hasPillageCancelRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getPillageCancelRequest());
      }
      if (hasPillageShowRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getPillageShowRequest());
      }
      if (hasCardGetCardsInfoRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getCardGetCardsInfoRequest());
      }
      if (hasCardEditCardListRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getCardEditCardListRequest());
      }
      if (hasCardLvUpRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getCardLvUpRequest());
      }
      if (hasCardChooseUseCardListRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getCardChooseUseCardListRequest());
      }
      if (hasPingRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getPingRequest());
      }
      if (hasFightGetGameAwardRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, getFightGetGameAwardRequest());
      }
      if (hasCardChangeMainCardRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, getCardChangeMainCardRequest());
      }
      if (hasGmRejectLoginRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(19, getGmRejectLoginRequest());
      }
      if (hasGmTerminatedServerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, getGmTerminatedServerRequest());
      }
      if (hasGmOpenLoginRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(21, getGmOpenLoginRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasFightClientReadyRequest()) {
          mergeFightClientReadyRequest(other.getFightClientReadyRequest());
        }
        if (other.hasFightLoadResourceCompleteRequest()) {
          mergeFightLoadResourceCompleteRequest(other.getFightLoadResourceCompleteRequest());
        }
        if (other.hasFightGameActionRequest()) {
          mergeFightGameActionRequest(other.getFightGameActionRequest());
        }
        if (other.hasFightGameOverRequest()) {
          mergeFightGameOverRequest(other.getFightGameOverRequest());
        }
        if (other.hasFightReadFrameRequest()) {
          mergeFightReadFrameRequest(other.getFightReadFrameRequest());
        }
        if (other.hasFightGetGameAwardRequest()) {
          mergeFightGetGameAwardRequest(other.getFightGetGameAwardRequest());
        }
        if (other.hasPillageRoleRequest()) {
          mergePillageRoleRequest(other.getPillageRoleRequest());
        }
        if (other.hasPillageCancelRequest()) {
          mergePillageCancelRequest(other.getPillageCancelRequest());
        }
        if (other.hasPillageShowRequest()) {
          mergePillageShowRequest(other.getPillageShowRequest());
        }
        if (other.hasCardGetCardsInfoRequest()) {
          mergeCardGetCardsInfoRequest(other.getCardGetCardsInfoRequest());
        }
        if (other.hasCardEditCardListRequest()) {
          mergeCardEditCardListRequest(other.getCardEditCardListRequest());
        }
        if (other.hasCardLvUpRequest()) {
          mergeCardLvUpRequest(other.getCardLvUpRequest());
        }
        if (other.hasCardChooseUseCardListRequest()) {
          mergeCardChooseUseCardListRequest(other.getCardChooseUseCardListRequest());
        }
        if (other.hasCardChangeMainCardRequest()) {
          mergeCardChangeMainCardRequest(other.getCardChangeMainCardRequest());
        }
        if (other.hasPingRequest()) {
          mergePingRequest(other.getPingRequest());
        }
        if (other.hasGmRejectLoginRequest()) {
          mergeGmRejectLoginRequest(other.getGmRejectLoginRequest());
        }
        if (other.hasGmTerminatedServerRequest()) {
          mergeGmTerminatedServerRequest(other.getGmTerminatedServerRequest());
        }
        if (other.hasGmOpenLoginRequest()) {
          mergeGmOpenLoginRequest(other.getGmOpenLoginRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.newBuilder();
              if (hasFightClientReadyRequest()) {
                subBuilder.mergeFrom(getFightClientReadyRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightClientReadyRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.newBuilder();
              if (hasFightLoadResourceCompleteRequest()) {
                subBuilder.mergeFrom(getFightLoadResourceCompleteRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightLoadResourceCompleteRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.newBuilder();
              if (hasFightGameActionRequest()) {
                subBuilder.mergeFrom(getFightGameActionRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightGameActionRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.newBuilder();
              if (hasFightGameOverRequest()) {
                subBuilder.mergeFrom(getFightGameOverRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightGameOverRequest(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.newBuilder();
              if (hasFightReadFrameRequest()) {
                subBuilder.mergeFrom(getFightReadFrameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightReadFrameRequest(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.newBuilder();
              if (hasPillageRoleRequest()) {
                subBuilder.mergeFrom(getPillageRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPillageRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.newBuilder();
              if (hasPillageCancelRequest()) {
                subBuilder.mergeFrom(getPillageCancelRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPillageCancelRequest(subBuilder.buildPartial());
              break;
            }
            case 90: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.newBuilder();
              if (hasPillageShowRequest()) {
                subBuilder.mergeFrom(getPillageShowRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPillageShowRequest(subBuilder.buildPartial());
              break;
            }
            case 98: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.newBuilder();
              if (hasCardGetCardsInfoRequest()) {
                subBuilder.mergeFrom(getCardGetCardsInfoRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCardGetCardsInfoRequest(subBuilder.buildPartial());
              break;
            }
            case 106: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.newBuilder();
              if (hasCardEditCardListRequest()) {
                subBuilder.mergeFrom(getCardEditCardListRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCardEditCardListRequest(subBuilder.buildPartial());
              break;
            }
            case 114: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.newBuilder();
              if (hasCardLvUpRequest()) {
                subBuilder.mergeFrom(getCardLvUpRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCardLvUpRequest(subBuilder.buildPartial());
              break;
            }
            case 122: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.newBuilder();
              if (hasCardChooseUseCardListRequest()) {
                subBuilder.mergeFrom(getCardChooseUseCardListRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCardChooseUseCardListRequest(subBuilder.buildPartial());
              break;
            }
            case 130: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.newBuilder();
              if (hasPingRequest()) {
                subBuilder.mergeFrom(getPingRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPingRequest(subBuilder.buildPartial());
              break;
            }
            case 138: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.newBuilder();
              if (hasFightGetGameAwardRequest()) {
                subBuilder.mergeFrom(getFightGetGameAwardRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightGetGameAwardRequest(subBuilder.buildPartial());
              break;
            }
            case 146: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.newBuilder();
              if (hasCardChangeMainCardRequest()) {
                subBuilder.mergeFrom(getCardChangeMainCardRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCardChangeMainCardRequest(subBuilder.buildPartial());
              break;
            }
            case 154: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.newBuilder();
              if (hasGmRejectLoginRequest()) {
                subBuilder.mergeFrom(getGmRejectLoginRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmRejectLoginRequest(subBuilder.buildPartial());
              break;
            }
            case 162: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.newBuilder();
              if (hasGmTerminatedServerRequest()) {
                subBuilder.mergeFrom(getGmTerminatedServerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmTerminatedServerRequest(subBuilder.buildPartial());
              break;
            }
            case 170: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.newBuilder();
              if (hasGmOpenLoginRequest()) {
                subBuilder.mergeFrom(getGmOpenLoginRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmOpenLoginRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.LoginCheckAccountRequest loginCheckAccountRequest = 1;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.LoginCreateRoleRequest loginCreateRoleRequest = 2;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.LoginGetRoleDataRequest loginGetRoleDataRequest = 3;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightClientReadyRequest fightClientReadyRequest = 4;
      public boolean hasFightClientReadyRequest() {
        return result.hasFightClientReadyRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest getFightClientReadyRequest() {
        return result.getFightClientReadyRequest();
      }
      public Builder setFightClientReadyRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightClientReadyRequest = true;
        result.fightClientReadyRequest_ = value;
        return this;
      }
      public Builder setFightClientReadyRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.Builder builderForValue) {
        result.hasFightClientReadyRequest = true;
        result.fightClientReadyRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightClientReadyRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest value) {
        if (result.hasFightClientReadyRequest() &&
            result.fightClientReadyRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.getDefaultInstance()) {
          result.fightClientReadyRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.newBuilder(result.fightClientReadyRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightClientReadyRequest_ = value;
        }
        result.hasFightClientReadyRequest = true;
        return this;
      }
      public Builder clearFightClientReadyRequest() {
        result.hasFightClientReadyRequest = false;
        result.fightClientReadyRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightClientReadyRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightLoadResourceCompleteRequest fightLoadResourceCompleteRequest = 5;
      public boolean hasFightLoadResourceCompleteRequest() {
        return result.hasFightLoadResourceCompleteRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest getFightLoadResourceCompleteRequest() {
        return result.getFightLoadResourceCompleteRequest();
      }
      public Builder setFightLoadResourceCompleteRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightLoadResourceCompleteRequest = true;
        result.fightLoadResourceCompleteRequest_ = value;
        return this;
      }
      public Builder setFightLoadResourceCompleteRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.Builder builderForValue) {
        result.hasFightLoadResourceCompleteRequest = true;
        result.fightLoadResourceCompleteRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightLoadResourceCompleteRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest value) {
        if (result.hasFightLoadResourceCompleteRequest() &&
            result.fightLoadResourceCompleteRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.getDefaultInstance()) {
          result.fightLoadResourceCompleteRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.newBuilder(result.fightLoadResourceCompleteRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightLoadResourceCompleteRequest_ = value;
        }
        result.hasFightLoadResourceCompleteRequest = true;
        return this;
      }
      public Builder clearFightLoadResourceCompleteRequest() {
        result.hasFightLoadResourceCompleteRequest = false;
        result.fightLoadResourceCompleteRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightLoadResourceCompleteRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightGameActionRequest fightGameActionRequest = 6;
      public boolean hasFightGameActionRequest() {
        return result.hasFightGameActionRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest getFightGameActionRequest() {
        return result.getFightGameActionRequest();
      }
      public Builder setFightGameActionRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightGameActionRequest = true;
        result.fightGameActionRequest_ = value;
        return this;
      }
      public Builder setFightGameActionRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.Builder builderForValue) {
        result.hasFightGameActionRequest = true;
        result.fightGameActionRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightGameActionRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest value) {
        if (result.hasFightGameActionRequest() &&
            result.fightGameActionRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.getDefaultInstance()) {
          result.fightGameActionRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.newBuilder(result.fightGameActionRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightGameActionRequest_ = value;
        }
        result.hasFightGameActionRequest = true;
        return this;
      }
      public Builder clearFightGameActionRequest() {
        result.hasFightGameActionRequest = false;
        result.fightGameActionRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameActionRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightGameOverRequest fightGameOverRequest = 7;
      public boolean hasFightGameOverRequest() {
        return result.hasFightGameOverRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest getFightGameOverRequest() {
        return result.getFightGameOverRequest();
      }
      public Builder setFightGameOverRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightGameOverRequest = true;
        result.fightGameOverRequest_ = value;
        return this;
      }
      public Builder setFightGameOverRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.Builder builderForValue) {
        result.hasFightGameOverRequest = true;
        result.fightGameOverRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightGameOverRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest value) {
        if (result.hasFightGameOverRequest() &&
            result.fightGameOverRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.getDefaultInstance()) {
          result.fightGameOverRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.newBuilder(result.fightGameOverRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightGameOverRequest_ = value;
        }
        result.hasFightGameOverRequest = true;
        return this;
      }
      public Builder clearFightGameOverRequest() {
        result.hasFightGameOverRequest = false;
        result.fightGameOverRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGameOverRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightReadFrameRequest fightReadFrameRequest = 8;
      public boolean hasFightReadFrameRequest() {
        return result.hasFightReadFrameRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest getFightReadFrameRequest() {
        return result.getFightReadFrameRequest();
      }
      public Builder setFightReadFrameRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightReadFrameRequest = true;
        result.fightReadFrameRequest_ = value;
        return this;
      }
      public Builder setFightReadFrameRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.Builder builderForValue) {
        result.hasFightReadFrameRequest = true;
        result.fightReadFrameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightReadFrameRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest value) {
        if (result.hasFightReadFrameRequest() &&
            result.fightReadFrameRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.getDefaultInstance()) {
          result.fightReadFrameRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.newBuilder(result.fightReadFrameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightReadFrameRequest_ = value;
        }
        result.hasFightReadFrameRequest = true;
        return this;
      }
      public Builder clearFightReadFrameRequest() {
        result.hasFightReadFrameRequest = false;
        result.fightReadFrameRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightReadFrameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.FightGetGameAwardRequest fightGetGameAwardRequest = 17;
      public boolean hasFightGetGameAwardRequest() {
        return result.hasFightGetGameAwardRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest getFightGetGameAwardRequest() {
        return result.getFightGetGameAwardRequest();
      }
      public Builder setFightGetGameAwardRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightGetGameAwardRequest = true;
        result.fightGetGameAwardRequest_ = value;
        return this;
      }
      public Builder setFightGetGameAwardRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.Builder builderForValue) {
        result.hasFightGetGameAwardRequest = true;
        result.fightGetGameAwardRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightGetGameAwardRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest value) {
        if (result.hasFightGetGameAwardRequest() &&
            result.fightGetGameAwardRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.getDefaultInstance()) {
          result.fightGetGameAwardRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.newBuilder(result.fightGetGameAwardRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightGetGameAwardRequest_ = value;
        }
        result.hasFightGetGameAwardRequest = true;
        return this;
      }
      public Builder clearFightGetGameAwardRequest() {
        result.hasFightGetGameAwardRequest = false;
        result.fightGetGameAwardRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.FightGetGameAwardRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PillageRoleRequest pillageRoleRequest = 9;
      public boolean hasPillageRoleRequest() {
        return result.hasPillageRoleRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest getPillageRoleRequest() {
        return result.getPillageRoleRequest();
      }
      public Builder setPillageRoleRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPillageRoleRequest = true;
        result.pillageRoleRequest_ = value;
        return this;
      }
      public Builder setPillageRoleRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.Builder builderForValue) {
        result.hasPillageRoleRequest = true;
        result.pillageRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePillageRoleRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest value) {
        if (result.hasPillageRoleRequest() &&
            result.pillageRoleRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.getDefaultInstance()) {
          result.pillageRoleRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.newBuilder(result.pillageRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pillageRoleRequest_ = value;
        }
        result.hasPillageRoleRequest = true;
        return this;
      }
      public Builder clearPillageRoleRequest() {
        result.hasPillageRoleRequest = false;
        result.pillageRoleRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PillageCancelRequest pillageCancelRequest = 10;
      public boolean hasPillageCancelRequest() {
        return result.hasPillageCancelRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest getPillageCancelRequest() {
        return result.getPillageCancelRequest();
      }
      public Builder setPillageCancelRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPillageCancelRequest = true;
        result.pillageCancelRequest_ = value;
        return this;
      }
      public Builder setPillageCancelRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.Builder builderForValue) {
        result.hasPillageCancelRequest = true;
        result.pillageCancelRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePillageCancelRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest value) {
        if (result.hasPillageCancelRequest() &&
            result.pillageCancelRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.getDefaultInstance()) {
          result.pillageCancelRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.newBuilder(result.pillageCancelRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pillageCancelRequest_ = value;
        }
        result.hasPillageCancelRequest = true;
        return this;
      }
      public Builder clearPillageCancelRequest() {
        result.hasPillageCancelRequest = false;
        result.pillageCancelRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageCancelRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PillageShowRequest pillageShowRequest = 11;
      public boolean hasPillageShowRequest() {
        return result.hasPillageShowRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest getPillageShowRequest() {
        return result.getPillageShowRequest();
      }
      public Builder setPillageShowRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPillageShowRequest = true;
        result.pillageShowRequest_ = value;
        return this;
      }
      public Builder setPillageShowRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.Builder builderForValue) {
        result.hasPillageShowRequest = true;
        result.pillageShowRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePillageShowRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest value) {
        if (result.hasPillageShowRequest() &&
            result.pillageShowRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.getDefaultInstance()) {
          result.pillageShowRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.newBuilder(result.pillageShowRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pillageShowRequest_ = value;
        }
        result.hasPillageShowRequest = true;
        return this;
      }
      public Builder clearPillageShowRequest() {
        result.hasPillageShowRequest = false;
        result.pillageShowRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.PillageShowRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardGetCardsInfoRequest cardGetCardsInfoRequest = 12;
      public boolean hasCardGetCardsInfoRequest() {
        return result.hasCardGetCardsInfoRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest getCardGetCardsInfoRequest() {
        return result.getCardGetCardsInfoRequest();
      }
      public Builder setCardGetCardsInfoRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCardGetCardsInfoRequest = true;
        result.cardGetCardsInfoRequest_ = value;
        return this;
      }
      public Builder setCardGetCardsInfoRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.Builder builderForValue) {
        result.hasCardGetCardsInfoRequest = true;
        result.cardGetCardsInfoRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeCardGetCardsInfoRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest value) {
        if (result.hasCardGetCardsInfoRequest() &&
            result.cardGetCardsInfoRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.getDefaultInstance()) {
          result.cardGetCardsInfoRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.newBuilder(result.cardGetCardsInfoRequest_).mergeFrom(value).buildPartial();
        } else {
          result.cardGetCardsInfoRequest_ = value;
        }
        result.hasCardGetCardsInfoRequest = true;
        return this;
      }
      public Builder clearCardGetCardsInfoRequest() {
        result.hasCardGetCardsInfoRequest = false;
        result.cardGetCardsInfoRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardGetCardsInfoRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardEditCardListRequest cardEditCardListRequest = 13;
      public boolean hasCardEditCardListRequest() {
        return result.hasCardEditCardListRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest getCardEditCardListRequest() {
        return result.getCardEditCardListRequest();
      }
      public Builder setCardEditCardListRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCardEditCardListRequest = true;
        result.cardEditCardListRequest_ = value;
        return this;
      }
      public Builder setCardEditCardListRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.Builder builderForValue) {
        result.hasCardEditCardListRequest = true;
        result.cardEditCardListRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeCardEditCardListRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest value) {
        if (result.hasCardEditCardListRequest() &&
            result.cardEditCardListRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.getDefaultInstance()) {
          result.cardEditCardListRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.newBuilder(result.cardEditCardListRequest_).mergeFrom(value).buildPartial();
        } else {
          result.cardEditCardListRequest_ = value;
        }
        result.hasCardEditCardListRequest = true;
        return this;
      }
      public Builder clearCardEditCardListRequest() {
        result.hasCardEditCardListRequest = false;
        result.cardEditCardListRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardEditCardListRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardLvUpRequest cardLvUpRequest = 14;
      public boolean hasCardLvUpRequest() {
        return result.hasCardLvUpRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest getCardLvUpRequest() {
        return result.getCardLvUpRequest();
      }
      public Builder setCardLvUpRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCardLvUpRequest = true;
        result.cardLvUpRequest_ = value;
        return this;
      }
      public Builder setCardLvUpRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.Builder builderForValue) {
        result.hasCardLvUpRequest = true;
        result.cardLvUpRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeCardLvUpRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest value) {
        if (result.hasCardLvUpRequest() &&
            result.cardLvUpRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.getDefaultInstance()) {
          result.cardLvUpRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.newBuilder(result.cardLvUpRequest_).mergeFrom(value).buildPartial();
        } else {
          result.cardLvUpRequest_ = value;
        }
        result.hasCardLvUpRequest = true;
        return this;
      }
      public Builder clearCardLvUpRequest() {
        result.hasCardLvUpRequest = false;
        result.cardLvUpRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardLvUpRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardChooseUseCardListRequest cardChooseUseCardListRequest = 15;
      public boolean hasCardChooseUseCardListRequest() {
        return result.hasCardChooseUseCardListRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest getCardChooseUseCardListRequest() {
        return result.getCardChooseUseCardListRequest();
      }
      public Builder setCardChooseUseCardListRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCardChooseUseCardListRequest = true;
        result.cardChooseUseCardListRequest_ = value;
        return this;
      }
      public Builder setCardChooseUseCardListRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.Builder builderForValue) {
        result.hasCardChooseUseCardListRequest = true;
        result.cardChooseUseCardListRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeCardChooseUseCardListRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest value) {
        if (result.hasCardChooseUseCardListRequest() &&
            result.cardChooseUseCardListRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.getDefaultInstance()) {
          result.cardChooseUseCardListRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.newBuilder(result.cardChooseUseCardListRequest_).mergeFrom(value).buildPartial();
        } else {
          result.cardChooseUseCardListRequest_ = value;
        }
        result.hasCardChooseUseCardListRequest = true;
        return this;
      }
      public Builder clearCardChooseUseCardListRequest() {
        result.hasCardChooseUseCardListRequest = false;
        result.cardChooseUseCardListRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChooseUseCardListRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.CardChangeMainCardRequest cardChangeMainCardRequest = 18;
      public boolean hasCardChangeMainCardRequest() {
        return result.hasCardChangeMainCardRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest getCardChangeMainCardRequest() {
        return result.getCardChangeMainCardRequest();
      }
      public Builder setCardChangeMainCardRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCardChangeMainCardRequest = true;
        result.cardChangeMainCardRequest_ = value;
        return this;
      }
      public Builder setCardChangeMainCardRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.Builder builderForValue) {
        result.hasCardChangeMainCardRequest = true;
        result.cardChangeMainCardRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeCardChangeMainCardRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest value) {
        if (result.hasCardChangeMainCardRequest() &&
            result.cardChangeMainCardRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.getDefaultInstance()) {
          result.cardChangeMainCardRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.newBuilder(result.cardChangeMainCardRequest_).mergeFrom(value).buildPartial();
        } else {
          result.cardChangeMainCardRequest_ = value;
        }
        result.hasCardChangeMainCardRequest = true;
        return this;
      }
      public Builder clearCardChangeMainCardRequest() {
        result.hasCardChangeMainCardRequest = false;
        result.cardChangeMainCardRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.CardChangeMainCardRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.PingRequest pingRequest = 16;
      public boolean hasPingRequest() {
        return result.hasPingRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest getPingRequest() {
        return result.getPingRequest();
      }
      public Builder setPingRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPingRequest = true;
        result.pingRequest_ = value;
        return this;
      }
      public Builder setPingRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.Builder builderForValue) {
        result.hasPingRequest = true;
        result.pingRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePingRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest value) {
        if (result.hasPingRequest() &&
            result.pingRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.getDefaultInstance()) {
          result.pingRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.newBuilder(result.pingRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pingRequest_ = value;
        }
        result.hasPingRequest = true;
        return this;
      }
      public Builder clearPingRequest() {
        result.hasPingRequest = false;
        result.pingRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.PingRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.GMRejectLoginRequest gmRejectLoginRequest = 19;
      public boolean hasGmRejectLoginRequest() {
        return result.hasGmRejectLoginRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest getGmRejectLoginRequest() {
        return result.getGmRejectLoginRequest();
      }
      public Builder setGmRejectLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmRejectLoginRequest = true;
        result.gmRejectLoginRequest_ = value;
        return this;
      }
      public Builder setGmRejectLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.Builder builderForValue) {
        result.hasGmRejectLoginRequest = true;
        result.gmRejectLoginRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmRejectLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest value) {
        if (result.hasGmRejectLoginRequest() &&
            result.gmRejectLoginRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.getDefaultInstance()) {
          result.gmRejectLoginRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.newBuilder(result.gmRejectLoginRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmRejectLoginRequest_ = value;
        }
        result.hasGmRejectLoginRequest = true;
        return this;
      }
      public Builder clearGmRejectLoginRequest() {
        result.hasGmRejectLoginRequest = false;
        result.gmRejectLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMRejectLoginRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.GMTerminatedServerRequest gmTerminatedServerRequest = 20;
      public boolean hasGmTerminatedServerRequest() {
        return result.hasGmTerminatedServerRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest getGmTerminatedServerRequest() {
        return result.getGmTerminatedServerRequest();
      }
      public Builder setGmTerminatedServerRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmTerminatedServerRequest = true;
        result.gmTerminatedServerRequest_ = value;
        return this;
      }
      public Builder setGmTerminatedServerRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.Builder builderForValue) {
        result.hasGmTerminatedServerRequest = true;
        result.gmTerminatedServerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmTerminatedServerRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest value) {
        if (result.hasGmTerminatedServerRequest() &&
            result.gmTerminatedServerRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.getDefaultInstance()) {
          result.gmTerminatedServerRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.newBuilder(result.gmTerminatedServerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmTerminatedServerRequest_ = value;
        }
        result.hasGmTerminatedServerRequest = true;
        return this;
      }
      public Builder clearGmTerminatedServerRequest() {
        result.hasGmTerminatedServerRequest = false;
        result.gmTerminatedServerRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMTerminatedServerRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.GMOpenLoginRequest gmOpenLoginRequest = 21;
      public boolean hasGmOpenLoginRequest() {
        return result.hasGmOpenLoginRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest getGmOpenLoginRequest() {
        return result.getGmOpenLoginRequest();
      }
      public Builder setGmOpenLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmOpenLoginRequest = true;
        result.gmOpenLoginRequest_ = value;
        return this;
      }
      public Builder setGmOpenLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.Builder builderForValue) {
        result.hasGmOpenLoginRequest = true;
        result.gmOpenLoginRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmOpenLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest value) {
        if (result.hasGmOpenLoginRequest() &&
            result.gmOpenLoginRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.getDefaultInstance()) {
          result.gmOpenLoginRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.newBuilder(result.gmOpenLoginRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmOpenLoginRequest_ = value;
        }
        result.hasGmOpenLoginRequest = true;
        return this;
      }
      public Builder clearGmOpenLoginRequest() {
        result.hasGmOpenLoginRequest = false;
        result.gmOpenLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.GMOpenLoginRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.CSMessage)
    }
    
    static {
      defaultInstance = new CSMessage(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.CSMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\0226com.randioo.owlof" +
      "war_server_simplify_protobuf.protocol\032\013L" +
      "ogin.proto\032\013Match.proto\032\013Fight.proto\032\rPi" +
      "llage.proto\032\nCard.proto\032\nPing.proto\032\010GM." +
      "proto\"\256\022\n\tCSMessage\022r\n\030loginCheckAccount" +
      "Request\030\001 \001(\0132P.com.randioo.owlofwar_ser" +
      "ver_simplify_protobuf.protocol.LoginChec" +
      "kAccountRequest\022n\n\026loginCreateRoleReques" +
      "t\030\002 \001(\0132N.com.randioo.owlofwar_server_si" +
      "mplify_protobuf.protocol.LoginCreateRole",
      "Request\022p\n\027loginGetRoleDataRequest\030\003 \001(\013" +
      "2O.com.randioo.owlofwar_server_simplify_" +
      "protobuf.protocol.LoginGetRoleDataReques" +
      "t\022p\n\027fightClientReadyRequest\030\004 \001(\0132O.com" +
      ".randioo.owlofwar_server_simplify_protob" +
      "uf.protocol.FightClientReadyRequest\022\202\001\n " +
      "fightLoadResourceCompleteRequest\030\005 \001(\0132X" +
      ".com.randioo.owlofwar_server_simplify_pr" +
      "otobuf.protocol.FightLoadResourceComplet" +
      "eRequest\022n\n\026fightGameActionRequest\030\006 \001(\013",
      "2N.com.randioo.owlofwar_server_simplify_" +
      "protobuf.protocol.FightGameActionRequest" +
      "\022j\n\024fightGameOverRequest\030\007 \001(\0132L.com.ran" +
      "dioo.owlofwar_server_simplify_protobuf.p" +
      "rotocol.FightGameOverRequest\022l\n\025fightRea" +
      "dFrameRequest\030\010 \001(\0132M.com.randioo.owlofw" +
      "ar_server_simplify_protobuf.protocol.Fig" +
      "htReadFrameRequest\022r\n\030fightGetGameAwardR" +
      "equest\030\021 \001(\0132P.com.randioo.owlofwar_serv" +
      "er_simplify_protobuf.protocol.FightGetGa",
      "meAwardRequest\022f\n\022pillageRoleRequest\030\t \001" +
      "(\0132J.com.randioo.owlofwar_server_simplif" +
      "y_protobuf.protocol.PillageRoleRequest\022j" +
      "\n\024pillageCancelRequest\030\n \001(\0132L.com.randi" +
      "oo.owlofwar_server_simplify_protobuf.pro" +
      "tocol.PillageCancelRequest\022f\n\022pillageSho" +
      "wRequest\030\013 \001(\0132J.com.randioo.owlofwar_se" +
      "rver_simplify_protobuf.protocol.PillageS" +
      "howRequest\022p\n\027cardGetCardsInfoRequest\030\014 " +
      "\001(\0132O.com.randioo.owlofwar_server_simpli",
      "fy_protobuf.protocol.CardGetCardsInfoReq" +
      "uest\022p\n\027cardEditCardListRequest\030\r \001(\0132O." +
      "com.randioo.owlofwar_server_simplify_pro" +
      "tobuf.protocol.CardEditCardListRequest\022`" +
      "\n\017cardLvUpRequest\030\016 \001(\0132G.com.randioo.ow" +
      "lofwar_server_simplify_protobuf.protocol" +
      ".CardLvUpRequest\022z\n\034cardChooseUseCardLis" +
      "tRequest\030\017 \001(\0132T.com.randioo.owlofwar_se" +
      "rver_simplify_protobuf.protocol.CardChoo" +
      "seUseCardListRequest\022t\n\031cardChangeMainCa",
      "rdRequest\030\022 \001(\0132Q.com.randioo.owlofwar_s" +
      "erver_simplify_protobuf.protocol.CardCha" +
      "ngeMainCardRequest\022X\n\013pingRequest\030\020 \001(\0132" +
      "C.com.randioo.owlofwar_server_simplify_p" +
      "rotobuf.protocol.PingRequest\022j\n\024gmReject" +
      "LoginRequest\030\023 \001(\0132L.com.randioo.owlofwa" +
      "r_server_simplify_protobuf.protocol.GMRe" +
      "jectLoginRequest\022t\n\031gmTerminatedServerRe" +
      "quest\030\024 \001(\0132Q.com.randioo.owlofwar_serve" +
      "r_simplify_protobuf.protocol.GMTerminate",
      "dServerRequest\022f\n\022gmOpenLoginRequest\030\025 \001" +
      "(\0132J.com.randioo.owlofwar_server_simplif" +
      "y_protobuf.protocol.GMOpenLoginRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_CSMessage_descriptor,
              new java.lang.String[] { "LoginCheckAccountRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "FightClientReadyRequest", "FightLoadResourceCompleteRequest", "FightGameActionRequest", "FightGameOverRequest", "FightReadFrameRequest", "FightGetGameAwardRequest", "PillageRoleRequest", "PillageCancelRequest", "PillageShowRequest", "CardGetCardsInfoRequest", "CardEditCardListRequest", "CardLvUpRequest", "CardChooseUseCardListRequest", "CardChangeMainCardRequest", "PingRequest", "GmRejectLoginRequest", "GmTerminatedServerRequest", "GmOpenLoginRequest", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.ClientMessage.CSMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Login.getDescriptor(),
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.getDescriptor(),
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Fight.getDescriptor(),
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Pillage.getDescriptor(),
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Card.getDescriptor(),
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Ping.getDescriptor(),
          com.randioo.owlofwar_server_simplify_protobuf.protocol.GM.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
