// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Market.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol;

public final class Market {
  private Market() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class MarketShowMarketItemRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketShowMarketItemRequest.newBuilder() to construct.
    private MarketShowMarketItemRequest() {
      initFields();
    }
    private MarketShowMarketItemRequest(boolean noInit) {}
    
    private static final MarketShowMarketItemRequest defaultInstance;
    public static MarketShowMarketItemRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketShowMarketItemRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketShowMarketItemRequest)
    }
    
    static {
      defaultInstance = new MarketShowMarketItemRequest(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketShowMarketItemRequest)
  }
  
  public static final class MarketShowMarketItemResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketShowMarketItemResponse.newBuilder() to construct.
    private MarketShowMarketItemResponse() {
      initFields();
    }
    private MarketShowMarketItemResponse(boolean noInit) {}
    
    private static final MarketShowMarketItemResponse defaultInstance;
    public static MarketShowMarketItemResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketShowMarketItemResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_fieldAccessorTable;
    }
    
    // optional bool isRefresh = 1;
    public static final int ISREFRESH_FIELD_NUMBER = 1;
    private boolean hasIsRefresh;
    private boolean isRefresh_ = false;
    public boolean hasIsRefresh() { return hasIsRefresh; }
    public boolean getIsRefresh() { return isRefresh_; }
    
    // optional int32 refreshCount = 2;
    public static final int REFRESHCOUNT_FIELD_NUMBER = 2;
    private boolean hasRefreshCount;
    private int refreshCount_ = 0;
    public boolean hasRefreshCount() { return hasRefreshCount; }
    public int getRefreshCount() { return refreshCount_; }
    
    // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketItemData marketItemData = 3;
    public static final int MARKETITEMDATA_FIELD_NUMBER = 3;
    private java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> marketItemData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> getMarketItemDataList() {
      return marketItemData_;
    }
    public int getMarketItemDataCount() { return marketItemData_.size(); }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData getMarketItemData(int index) {
      return marketItemData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIsRefresh()) {
        output.writeBool(1, getIsRefresh());
      }
      if (hasRefreshCount()) {
        output.writeInt32(2, getRefreshCount());
      }
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIsRefresh()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getIsRefresh());
      }
      if (hasRefreshCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getRefreshCount());
      }
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.marketItemData_ != java.util.Collections.EMPTY_LIST) {
          result.marketItemData_ =
            java.util.Collections.unmodifiableList(result.marketItemData_);
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse.getDefaultInstance()) return this;
        if (other.hasIsRefresh()) {
          setIsRefresh(other.getIsRefresh());
        }
        if (other.hasRefreshCount()) {
          setRefreshCount(other.getRefreshCount());
        }
        if (!other.marketItemData_.isEmpty()) {
          if (result.marketItemData_.isEmpty()) {
            result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
          }
          result.marketItemData_.addAll(other.marketItemData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setIsRefresh(input.readBool());
              break;
            }
            case 16: {
              setRefreshCount(input.readInt32());
              break;
            }
            case 26: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMarketItemData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional bool isRefresh = 1;
      public boolean hasIsRefresh() {
        return result.hasIsRefresh();
      }
      public boolean getIsRefresh() {
        return result.getIsRefresh();
      }
      public Builder setIsRefresh(boolean value) {
        result.hasIsRefresh = true;
        result.isRefresh_ = value;
        return this;
      }
      public Builder clearIsRefresh() {
        result.hasIsRefresh = false;
        result.isRefresh_ = false;
        return this;
      }
      
      // optional int32 refreshCount = 2;
      public boolean hasRefreshCount() {
        return result.hasRefreshCount();
      }
      public int getRefreshCount() {
        return result.getRefreshCount();
      }
      public Builder setRefreshCount(int value) {
        result.hasRefreshCount = true;
        result.refreshCount_ = value;
        return this;
      }
      public Builder clearRefreshCount() {
        result.hasRefreshCount = false;
        result.refreshCount_ = 0;
        return this;
      }
      
      // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketItemData marketItemData = 3;
      public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> getMarketItemDataList() {
        return java.util.Collections.unmodifiableList(result.marketItemData_);
      }
      public int getMarketItemDataCount() {
        return result.getMarketItemDataCount();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData getMarketItemData(int index) {
        return result.getMarketItemData(index);
      }
      public Builder setMarketItemData(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.marketItemData_.set(index, value);
        return this;
      }
      public Builder setMarketItemData(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.Builder builderForValue) {
        result.marketItemData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMarketItemData(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(value);
        return this;
      }
      public Builder addMarketItemData(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.Builder builderForValue) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMarketItemData(
          java.lang.Iterable<? extends com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> values) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
        }
        super.addAll(values, result.marketItemData_);
        return this;
      }
      public Builder clearMarketItemData() {
        result.marketItemData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketShowMarketItemResponse)
    }
    
    static {
      defaultInstance = new MarketShowMarketItemResponse(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketShowMarketItemResponse)
  }
  
  public static final class MarketBuyMarketItemRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketBuyMarketItemRequest.newBuilder() to construct.
    private MarketBuyMarketItemRequest() {
      initFields();
    }
    private MarketBuyMarketItemRequest(boolean noInit) {}
    
    private static final MarketBuyMarketItemRequest defaultInstance;
    public static MarketBuyMarketItemRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketBuyMarketItemRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_fieldAccessorTable;
    }
    
    // optional int32 index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private boolean hasIndex;
    private int index_ = 0;
    public boolean hasIndex() { return hasIndex; }
    public int getIndex() { return index_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIndex()) {
        output.writeInt32(1, getIndex());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getIndex());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setIndex(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 index = 1;
      public boolean hasIndex() {
        return result.hasIndex();
      }
      public int getIndex() {
        return result.getIndex();
      }
      public Builder setIndex(int value) {
        result.hasIndex = true;
        result.index_ = value;
        return this;
      }
      public Builder clearIndex() {
        result.hasIndex = false;
        result.index_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketBuyMarketItemRequest)
    }
    
    static {
      defaultInstance = new MarketBuyMarketItemRequest(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketBuyMarketItemRequest)
  }
  
  public static final class MarketBuyMarketItemResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketBuyMarketItemResponse.newBuilder() to construct.
    private MarketBuyMarketItemResponse() {
      initFields();
    }
    private MarketBuyMarketItemResponse(boolean noInit) {}
    
    private static final MarketBuyMarketItemResponse defaultInstance;
    public static MarketBuyMarketItemResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketBuyMarketItemResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 0;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional int32 buyCount = 2;
    public static final int BUYCOUNT_FIELD_NUMBER = 2;
    private boolean hasBuyCount;
    private int buyCount_ = 0;
    public boolean hasBuyCount() { return hasBuyCount; }
    public int getBuyCount() { return buyCount_; }
    
    // optional int32 dayBuyCount = 3;
    public static final int DAYBUYCOUNT_FIELD_NUMBER = 3;
    private boolean hasDayBuyCount;
    private int dayBuyCount_ = 0;
    public boolean hasDayBuyCount() { return hasDayBuyCount; }
    public int getDayBuyCount() { return dayBuyCount_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasBuyCount()) {
        output.writeInt32(2, getBuyCount());
      }
      if (hasDayBuyCount()) {
        output.writeInt32(3, getDayBuyCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasBuyCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getBuyCount());
      }
      if (hasDayBuyCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getDayBuyCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasBuyCount()) {
          setBuyCount(other.getBuyCount());
        }
        if (other.hasDayBuyCount()) {
          setDayBuyCount(other.getDayBuyCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 16: {
              setBuyCount(input.readInt32());
              break;
            }
            case 24: {
              setDayBuyCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1;
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 0;
        return this;
      }
      
      // optional int32 buyCount = 2;
      public boolean hasBuyCount() {
        return result.hasBuyCount();
      }
      public int getBuyCount() {
        return result.getBuyCount();
      }
      public Builder setBuyCount(int value) {
        result.hasBuyCount = true;
        result.buyCount_ = value;
        return this;
      }
      public Builder clearBuyCount() {
        result.hasBuyCount = false;
        result.buyCount_ = 0;
        return this;
      }
      
      // optional int32 dayBuyCount = 3;
      public boolean hasDayBuyCount() {
        return result.hasDayBuyCount();
      }
      public int getDayBuyCount() {
        return result.getDayBuyCount();
      }
      public Builder setDayBuyCount(int value) {
        result.hasDayBuyCount = true;
        result.dayBuyCount_ = value;
        return this;
      }
      public Builder clearDayBuyCount() {
        result.hasDayBuyCount = false;
        result.dayBuyCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketBuyMarketItemResponse)
    }
    
    static {
      defaultInstance = new MarketBuyMarketItemResponse(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketBuyMarketItemResponse)
  }
  
  public static final class MarketArtificialRefreshRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketArtificialRefreshRequest.newBuilder() to construct.
    private MarketArtificialRefreshRequest() {
      initFields();
    }
    private MarketArtificialRefreshRequest(boolean noInit) {}
    
    private static final MarketArtificialRefreshRequest defaultInstance;
    public static MarketArtificialRefreshRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketArtificialRefreshRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketArtificialRefreshRequest)
    }
    
    static {
      defaultInstance = new MarketArtificialRefreshRequest(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketArtificialRefreshRequest)
  }
  
  public static final class MarketArtificialRefreshResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketArtificialRefreshResponse.newBuilder() to construct.
    private MarketArtificialRefreshResponse() {
      initFields();
    }
    private MarketArtificialRefreshResponse(boolean noInit) {}
    
    private static final MarketArtificialRefreshResponse defaultInstance;
    public static MarketArtificialRefreshResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketArtificialRefreshResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 0;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional int32 refreshCount = 2;
    public static final int REFRESHCOUNT_FIELD_NUMBER = 2;
    private boolean hasRefreshCount;
    private int refreshCount_ = 0;
    public boolean hasRefreshCount() { return hasRefreshCount; }
    public int getRefreshCount() { return refreshCount_; }
    
    // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketItemData marketItemData = 3;
    public static final int MARKETITEMDATA_FIELD_NUMBER = 3;
    private java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> marketItemData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> getMarketItemDataList() {
      return marketItemData_;
    }
    public int getMarketItemDataCount() { return marketItemData_.size(); }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData getMarketItemData(int index) {
      return marketItemData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasRefreshCount()) {
        output.writeInt32(2, getRefreshCount());
      }
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasRefreshCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getRefreshCount());
      }
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.marketItemData_ != java.util.Collections.EMPTY_LIST) {
          result.marketItemData_ =
            java.util.Collections.unmodifiableList(result.marketItemData_);
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasRefreshCount()) {
          setRefreshCount(other.getRefreshCount());
        }
        if (!other.marketItemData_.isEmpty()) {
          if (result.marketItemData_.isEmpty()) {
            result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
          }
          result.marketItemData_.addAll(other.marketItemData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 16: {
              setRefreshCount(input.readInt32());
              break;
            }
            case 26: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMarketItemData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1;
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 0;
        return this;
      }
      
      // optional int32 refreshCount = 2;
      public boolean hasRefreshCount() {
        return result.hasRefreshCount();
      }
      public int getRefreshCount() {
        return result.getRefreshCount();
      }
      public Builder setRefreshCount(int value) {
        result.hasRefreshCount = true;
        result.refreshCount_ = value;
        return this;
      }
      public Builder clearRefreshCount() {
        result.hasRefreshCount = false;
        result.refreshCount_ = 0;
        return this;
      }
      
      // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketItemData marketItemData = 3;
      public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> getMarketItemDataList() {
        return java.util.Collections.unmodifiableList(result.marketItemData_);
      }
      public int getMarketItemDataCount() {
        return result.getMarketItemDataCount();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData getMarketItemData(int index) {
        return result.getMarketItemData(index);
      }
      public Builder setMarketItemData(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.marketItemData_.set(index, value);
        return this;
      }
      public Builder setMarketItemData(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.Builder builderForValue) {
        result.marketItemData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMarketItemData(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(value);
        return this;
      }
      public Builder addMarketItemData(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData.Builder builderForValue) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMarketItemData(
          java.lang.Iterable<? extends com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData> values) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.MarketItemData>();
        }
        super.addAll(values, result.marketItemData_);
        return this;
      }
      public Builder clearMarketItemData() {
        result.marketItemData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketArtificialRefreshResponse)
    }
    
    static {
      defaultInstance = new MarketArtificialRefreshResponse(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.MarketArtificialRefreshResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Market.proto\0226com.randioo.owlofwar_ser" +
      "ver_simplify_protobuf.protocol\032\014Entity.p" +
      "roto\"\035\n\033MarketShowMarketItemRequest\"\247\001\n\034" +
      "MarketShowMarketItemResponse\022\021\n\tisRefres" +
      "h\030\001 \001(\010\022\024\n\014refreshCount\030\002 \001(\005\022^\n\016marketI" +
      "temData\030\003 \003(\0132F.com.randioo.owlofwar_ser" +
      "ver_simplify_protobuf.protocol.MarketIte" +
      "mData\"+\n\032MarketBuyMarketItemRequest\022\r\n\005i" +
      "ndex\030\001 \001(\005\"W\n\033MarketBuyMarketItemRespons" +
      "e\022\021\n\terrorCode\030\001 \001(\005\022\020\n\010buyCount\030\002 \001(\005\022\023",
      "\n\013dayBuyCount\030\003 \001(\005\" \n\036MarketArtificialR" +
      "efreshRequest\"\252\001\n\037MarketArtificialRefres" +
      "hResponse\022\021\n\terrorCode\030\001 \001(\005\022\024\n\014refreshC" +
      "ount\030\002 \001(\005\022^\n\016marketItemData\030\003 \003(\0132F.com" +
      ".randioo.owlofwar_server_simplify_protob" +
      "uf.protocol.MarketItemData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemRequest.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketShowMarketItemResponse_descriptor,
              new java.lang.String[] { "IsRefresh", "RefreshCount", "MarketItemData", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketShowMarketItemResponse.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemRequest_descriptor,
              new java.lang.String[] { "Index", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemRequest.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketBuyMarketItemResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "BuyCount", "DayBuyCount", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketBuyMarketItemResponse.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshRequest.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_MarketArtificialRefreshResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "RefreshCount", "MarketItemData", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Market.MarketArtificialRefreshResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
