// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Match.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol;

public final class Match {
  private Match() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCMatchComplete extends
      com.google.protobuf.GeneratedMessage {
    // Use SCMatchComplete.newBuilder() to construct.
    private SCMatchComplete() {
      initFields();
    }
    private SCMatchComplete(boolean noInit) {}
    
    private static final SCMatchComplete defaultInstance;
    public static SCMatchComplete getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCMatchComplete getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCMatchComplete)
    }
    
    static {
      defaultInstance = new SCMatchComplete(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCMatchComplete)
  }
  
  public static final class SCMatchCancel extends
      com.google.protobuf.GeneratedMessage {
    // Use SCMatchCancel.newBuilder() to construct.
    private SCMatchCancel() {
      initFields();
    }
    private SCMatchCancel(boolean noInit) {}
    
    private static final SCMatchCancel defaultInstance;
    public static SCMatchCancel getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCMatchCancel getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCMatchCancel)
    }
    
    static {
      defaultInstance = new SCMatchCancel(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCMatchCancel)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Match.proto\0226com.randioo.owlofwar_serv" +
      "er_simplify_protobuf.protocol\"\021\n\017SCMatch" +
      "Complete\"\017\n\rSCMatchCancel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchComplete_descriptor,
              new java.lang.String[] { },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchComplete.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCMatchCancel_descriptor,
              new java.lang.String[] { },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Match.SCMatchCancel.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
