// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Role.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol;

public final class Role {
  private Role() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCRoleAddMoney extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRoleAddMoney.newBuilder() to construct.
    private SCRoleAddMoney() {
      initFields();
    }
    private SCRoleAddMoney(boolean noInit) {}
    
    private static final SCRoleAddMoney defaultInstance;
    public static SCRoleAddMoney getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRoleAddMoney getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_fieldAccessorTable;
    }
    
    // optional int32 addValue = 1;
    public static final int ADDVALUE_FIELD_NUMBER = 1;
    private boolean hasAddValue;
    private int addValue_ = 0;
    public boolean hasAddValue() { return hasAddValue; }
    public int getAddValue() { return addValue_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAddValue()) {
        output.writeInt32(1, getAddValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAddValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getAddValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney.getDefaultInstance()) return this;
        if (other.hasAddValue()) {
          setAddValue(other.getAddValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setAddValue(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 addValue = 1;
      public boolean hasAddValue() {
        return result.hasAddValue();
      }
      public int getAddValue() {
        return result.getAddValue();
      }
      public Builder setAddValue(int value) {
        result.hasAddValue = true;
        result.addValue_ = value;
        return this;
      }
      public Builder clearAddValue() {
        result.hasAddValue = false;
        result.addValue_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleAddMoney)
    }
    
    static {
      defaultInstance = new SCRoleAddMoney(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleAddMoney)
  }
  
  public static final class SCRoleAddGold extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRoleAddGold.newBuilder() to construct.
    private SCRoleAddGold() {
      initFields();
    }
    private SCRoleAddGold(boolean noInit) {}
    
    private static final SCRoleAddGold defaultInstance;
    public static SCRoleAddGold getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRoleAddGold getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_fieldAccessorTable;
    }
    
    // optional int32 addValue = 1;
    public static final int ADDVALUE_FIELD_NUMBER = 1;
    private boolean hasAddValue;
    private int addValue_ = 0;
    public boolean hasAddValue() { return hasAddValue; }
    public int getAddValue() { return addValue_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAddValue()) {
        output.writeInt32(1, getAddValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAddValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getAddValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold.getDefaultInstance()) return this;
        if (other.hasAddValue()) {
          setAddValue(other.getAddValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setAddValue(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 addValue = 1;
      public boolean hasAddValue() {
        return result.hasAddValue();
      }
      public int getAddValue() {
        return result.getAddValue();
      }
      public Builder setAddValue(int value) {
        result.hasAddValue = true;
        result.addValue_ = value;
        return this;
      }
      public Builder clearAddValue() {
        result.hasAddValue = false;
        result.addValue_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleAddGold)
    }
    
    static {
      defaultInstance = new SCRoleAddGold(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleAddGold)
  }
  
  public static final class RoleInfoSelectRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleInfoSelectRequest.newBuilder() to construct.
    private RoleInfoSelectRequest() {
      initFields();
    }
    private RoleInfoSelectRequest(boolean noInit) {}
    
    private static final RoleInfoSelectRequest defaultInstance;
    public static RoleInfoSelectRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleInfoSelectRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_fieldAccessorTable;
    }
    
    // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
    public static final int ROLEINFOTYPE_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> roleInfoType_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
      return roleInfoType_;
    }
    public int getRoleInfoTypeCount() { return roleInfoType_.size(); }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
      return roleInfoType_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
        output.writeEnum(1, element.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(element.getNumber());
        }
        size += dataSize;
        size += 1 * getRoleInfoTypeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.roleInfoType_ != java.util.Collections.EMPTY_LIST) {
          result.roleInfoType_ =
            java.util.Collections.unmodifiableList(result.roleInfoType_);
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.getDefaultInstance()) return this;
        if (!other.roleInfoType_.isEmpty()) {
          if (result.roleInfoType_.isEmpty()) {
            result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
          }
          result.roleInfoType_.addAll(other.roleInfoType_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                addRoleInfoType(value);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  addRoleInfoType(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
      public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
        return java.util.Collections.unmodifiableList(result.roleInfoType_);
      }
      public int getRoleInfoTypeCount() {
        return result.getRoleInfoTypeCount();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
        return result.getRoleInfoType(index);
      }
      public Builder setRoleInfoType(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.roleInfoType_.set(index, value);
        return this;
      }
      public Builder addRoleInfoType(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        result.roleInfoType_.add(value);
        return this;
      }
      public Builder addAllRoleInfoType(
          java.lang.Iterable<? extends com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> values) {
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        super.addAll(values, result.roleInfoType_);
        return this;
      }
      public Builder clearRoleInfoType() {
        result.roleInfoType_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectRequest)
    }
    
    static {
      defaultInstance = new RoleInfoSelectRequest(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectRequest)
  }
  
  public static final class RoleInfoSelectResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleInfoSelectResponse.newBuilder() to construct.
    private RoleInfoSelectResponse() {
      initFields();
    }
    private RoleInfoSelectResponse(boolean noInit) {}
    
    private static final RoleInfoSelectResponse defaultInstance;
    public static RoleInfoSelectResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleInfoSelectResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_fieldAccessorTable;
    }
    
    // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
    public static final int ROLEINFOTYPE_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> roleInfoType_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
      return roleInfoType_;
    }
    public int getRoleInfoTypeCount() { return roleInfoType_.size(); }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
      return roleInfoType_.get(index);
    }
    
    // optional int32 money = 2;
    public static final int MONEY_FIELD_NUMBER = 2;
    private boolean hasMoney;
    private int money_ = 0;
    public boolean hasMoney() { return hasMoney; }
    public int getMoney() { return money_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
        output.writeEnum(1, element.getNumber());
      }
      if (hasMoney()) {
        output.writeInt32(2, getMoney());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(element.getNumber());
        }
        size += dataSize;
        size += 1 * getRoleInfoTypeList().size();
      }
      if (hasMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getMoney());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.roleInfoType_ != java.util.Collections.EMPTY_LIST) {
          result.roleInfoType_ =
            java.util.Collections.unmodifiableList(result.roleInfoType_);
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.getDefaultInstance()) return this;
        if (!other.roleInfoType_.isEmpty()) {
          if (result.roleInfoType_.isEmpty()) {
            result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
          }
          result.roleInfoType_.addAll(other.roleInfoType_);
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                addRoleInfoType(value);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  addRoleInfoType(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 16: {
              setMoney(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
      public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
        return java.util.Collections.unmodifiableList(result.roleInfoType_);
      }
      public int getRoleInfoTypeCount() {
        return result.getRoleInfoTypeCount();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
        return result.getRoleInfoType(index);
      }
      public Builder setRoleInfoType(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.roleInfoType_.set(index, value);
        return this;
      }
      public Builder addRoleInfoType(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        result.roleInfoType_.add(value);
        return this;
      }
      public Builder addAllRoleInfoType(
          java.lang.Iterable<? extends com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> values) {
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        super.addAll(values, result.roleInfoType_);
        return this;
      }
      public Builder clearRoleInfoType() {
        result.roleInfoType_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int32 money = 2;
      public boolean hasMoney() {
        return result.hasMoney();
      }
      public int getMoney() {
        return result.getMoney();
      }
      public Builder setMoney(int value) {
        result.hasMoney = true;
        result.money_ = value;
        return this;
      }
      public Builder clearMoney() {
        result.hasMoney = false;
        result.money_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectResponse)
    }
    
    static {
      defaultInstance = new RoleInfoSelectResponse(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRole.proto\0226com.randioo.owlofwar_serve" +
      "r_simplify_protobuf.protocol\032\014Entity.pro" +
      "to\"\"\n\016SCRoleAddMoney\022\020\n\010addValue\030\001 \001(\005\"!" +
      "\n\rSCRoleAddGold\022\020\n\010addValue\030\001 \001(\005\"s\n\025Rol" +
      "eInfoSelectRequest\022Z\n\014roleInfoType\030\001 \003(\016" +
      "2D.com.randioo.owlofwar_server_simplify_" +
      "protobuf.protocol.RoleInfoType\"\203\001\n\026RoleI" +
      "nfoSelectResponse\022Z\n\014roleInfoType\030\001 \003(\0162" +
      "D.com.randioo.owlofwar_server_simplify_p" +
      "rotobuf.protocol.RoleInfoType\022\r\n\005money\030\002",
      " \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddMoney_descriptor,
              new java.lang.String[] { "AddValue", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddMoney.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleAddGold_descriptor,
              new java.lang.String[] { "AddValue", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleAddGold.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor,
              new java.lang.String[] { "RoleInfoType", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor,
              new java.lang.String[] { "RoleInfoType", "Money", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
