// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Role.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol;

public final class Role {
  private Role() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCRoleMoney extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRoleMoney.newBuilder() to construct.
    private SCRoleMoney() {
      initFields();
    }
    private SCRoleMoney(boolean noInit) {}
    
    private static final SCRoleMoney defaultInstance;
    public static SCRoleMoney getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRoleMoney getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_fieldAccessorTable;
    }
    
    // optional int32 money = 1;
    public static final int MONEY_FIELD_NUMBER = 1;
    private boolean hasMoney;
    private int money_ = 0;
    public boolean hasMoney() { return hasMoney; }
    public int getMoney() { return money_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMoney()) {
        output.writeInt32(1, getMoney());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getMoney());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney.getDefaultInstance()) return this;
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMoney(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 money = 1;
      public boolean hasMoney() {
        return result.hasMoney();
      }
      public int getMoney() {
        return result.getMoney();
      }
      public Builder setMoney(int value) {
        result.hasMoney = true;
        result.money_ = value;
        return this;
      }
      public Builder clearMoney() {
        result.hasMoney = false;
        result.money_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleMoney)
    }
    
    static {
      defaultInstance = new SCRoleMoney(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleMoney)
  }
  
  public static final class SCRoleGold extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRoleGold.newBuilder() to construct.
    private SCRoleGold() {
      initFields();
    }
    private SCRoleGold(boolean noInit) {}
    
    private static final SCRoleGold defaultInstance;
    public static SCRoleGold getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRoleGold getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_fieldAccessorTable;
    }
    
    // optional int32 gold = 1;
    public static final int GOLD_FIELD_NUMBER = 1;
    private boolean hasGold;
    private int gold_ = 0;
    public boolean hasGold() { return hasGold; }
    public int getGold() { return gold_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGold()) {
        output.writeInt32(1, getGold());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGold()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getGold());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold.getDefaultInstance()) return this;
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setGold(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 gold = 1;
      public boolean hasGold() {
        return result.hasGold();
      }
      public int getGold() {
        return result.getGold();
      }
      public Builder setGold(int value) {
        result.hasGold = true;
        result.gold_ = value;
        return this;
      }
      public Builder clearGold() {
        result.hasGold = false;
        result.gold_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleGold)
    }
    
    static {
      defaultInstance = new SCRoleGold(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRoleGold)
  }
  
  public static final class RoleInfoSelectRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleInfoSelectRequest.newBuilder() to construct.
    private RoleInfoSelectRequest() {
      initFields();
    }
    private RoleInfoSelectRequest(boolean noInit) {}
    
    private static final RoleInfoSelectRequest defaultInstance;
    public static RoleInfoSelectRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleInfoSelectRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_fieldAccessorTable;
    }
    
    // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
    public static final int ROLEINFOTYPE_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> roleInfoType_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
      return roleInfoType_;
    }
    public int getRoleInfoTypeCount() { return roleInfoType_.size(); }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
      return roleInfoType_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
        output.writeEnum(1, element.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(element.getNumber());
        }
        size += dataSize;
        size += 1 * getRoleInfoTypeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.roleInfoType_ != java.util.Collections.EMPTY_LIST) {
          result.roleInfoType_ =
            java.util.Collections.unmodifiableList(result.roleInfoType_);
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.getDefaultInstance()) return this;
        if (!other.roleInfoType_.isEmpty()) {
          if (result.roleInfoType_.isEmpty()) {
            result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
          }
          result.roleInfoType_.addAll(other.roleInfoType_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                addRoleInfoType(value);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  addRoleInfoType(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
      public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
        return java.util.Collections.unmodifiableList(result.roleInfoType_);
      }
      public int getRoleInfoTypeCount() {
        return result.getRoleInfoTypeCount();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
        return result.getRoleInfoType(index);
      }
      public Builder setRoleInfoType(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.roleInfoType_.set(index, value);
        return this;
      }
      public Builder addRoleInfoType(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        result.roleInfoType_.add(value);
        return this;
      }
      public Builder addAllRoleInfoType(
          java.lang.Iterable<? extends com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> values) {
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        super.addAll(values, result.roleInfoType_);
        return this;
      }
      public Builder clearRoleInfoType() {
        result.roleInfoType_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectRequest)
    }
    
    static {
      defaultInstance = new RoleInfoSelectRequest(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectRequest)
  }
  
  public static final class RoleInfoSelectResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleInfoSelectResponse.newBuilder() to construct.
    private RoleInfoSelectResponse() {
      initFields();
    }
    private RoleInfoSelectResponse(boolean noInit) {}
    
    private static final RoleInfoSelectResponse defaultInstance;
    public static RoleInfoSelectResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleInfoSelectResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_fieldAccessorTable;
    }
    
    // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
    public static final int ROLEINFOTYPE_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> roleInfoType_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
      return roleInfoType_;
    }
    public int getRoleInfoTypeCount() { return roleInfoType_.size(); }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
      return roleInfoType_.get(index);
    }
    
    // optional int32 money = 2;
    public static final int MONEY_FIELD_NUMBER = 2;
    private boolean hasMoney;
    private int money_ = 0;
    public boolean hasMoney() { return hasMoney; }
    public int getMoney() { return money_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
        output.writeEnum(1, element.getNumber());
      }
      if (hasMoney()) {
        output.writeInt32(2, getMoney());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType element : getRoleInfoTypeList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(element.getNumber());
        }
        size += dataSize;
        size += 1 * getRoleInfoTypeList().size();
      }
      if (hasMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getMoney());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.roleInfoType_ != java.util.Collections.EMPTY_LIST) {
          result.roleInfoType_ =
            java.util.Collections.unmodifiableList(result.roleInfoType_);
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.getDefaultInstance()) return this;
        if (!other.roleInfoType_.isEmpty()) {
          if (result.roleInfoType_.isEmpty()) {
            result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
          }
          result.roleInfoType_.addAll(other.roleInfoType_);
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                addRoleInfoType(value);
              }
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value = com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  addRoleInfoType(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 16: {
              setMoney(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoType roleInfoType = 1;
      public java.util.List<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> getRoleInfoTypeList() {
        return java.util.Collections.unmodifiableList(result.roleInfoType_);
      }
      public int getRoleInfoTypeCount() {
        return result.getRoleInfoTypeCount();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType getRoleInfoType(int index) {
        return result.getRoleInfoType(index);
      }
      public Builder setRoleInfoType(int index, com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.roleInfoType_.set(index, value);
        return this;
      }
      public Builder addRoleInfoType(com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        result.roleInfoType_.add(value);
        return this;
      }
      public Builder addAllRoleInfoType(
          java.lang.Iterable<? extends com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType> values) {
        if (result.roleInfoType_.isEmpty()) {
          result.roleInfoType_ = new java.util.ArrayList<com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.RoleInfoType>();
        }
        super.addAll(values, result.roleInfoType_);
        return this;
      }
      public Builder clearRoleInfoType() {
        result.roleInfoType_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int32 money = 2;
      public boolean hasMoney() {
        return result.hasMoney();
      }
      public int getMoney() {
        return result.getMoney();
      }
      public Builder setMoney(int value) {
        result.hasMoney = true;
        result.money_ = value;
        return this;
      }
      public Builder clearMoney() {
        result.hasMoney = false;
        result.money_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectResponse)
    }
    
    static {
      defaultInstance = new RoleInfoSelectResponse(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.RoleInfoSelectResponse)
  }
  
  public static final class SCRolePoint extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRolePoint.newBuilder() to construct.
    private SCRolePoint() {
      initFields();
    }
    private SCRolePoint(boolean noInit) {}
    
    private static final SCRolePoint defaultInstance;
    public static SCRolePoint getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRolePoint getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_fieldAccessorTable;
    }
    
    // optional int32 point = 1;
    public static final int POINT_FIELD_NUMBER = 1;
    private boolean hasPoint;
    private int point_ = 0;
    public boolean hasPoint() { return hasPoint; }
    public int getPoint() { return point_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPoint()) {
        output.writeInt32(1, getPoint());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPoint()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getPoint());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint.getDefaultInstance()) return this;
        if (other.hasPoint()) {
          setPoint(other.getPoint());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setPoint(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 point = 1;
      public boolean hasPoint() {
        return result.hasPoint();
      }
      public int getPoint() {
        return result.getPoint();
      }
      public Builder setPoint(int value) {
        result.hasPoint = true;
        result.point_ = value;
        return this;
      }
      public Builder clearPoint() {
        result.hasPoint = false;
        result.point_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRolePoint)
    }
    
    static {
      defaultInstance = new SCRolePoint(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.SCRolePoint)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRole.proto\0226com.randioo.owlofwar_serve" +
      "r_simplify_protobuf.protocol\032\014Entity.pro" +
      "to\"\034\n\013SCRoleMoney\022\r\n\005money\030\001 \001(\005\"\032\n\nSCRo" +
      "leGold\022\014\n\004gold\030\001 \001(\005\"s\n\025RoleInfoSelectRe" +
      "quest\022Z\n\014roleInfoType\030\001 \003(\0162D.com.randio" +
      "o.owlofwar_server_simplify_protobuf.prot" +
      "ocol.RoleInfoType\"\203\001\n\026RoleInfoSelectResp" +
      "onse\022Z\n\014roleInfoType\030\001 \003(\0162D.com.randioo" +
      ".owlofwar_server_simplify_protobuf.proto" +
      "col.RoleInfoType\022\r\n\005money\030\002 \001(\005\"\034\n\013SCRol",
      "ePoint\022\r\n\005point\030\001 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleMoney_descriptor,
              new java.lang.String[] { "Money", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleMoney.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRoleGold_descriptor,
              new java.lang.String[] { "Gold", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRoleGold.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectRequest_descriptor,
              new java.lang.String[] { "RoleInfoType", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectRequest.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_RoleInfoSelectResponse_descriptor,
              new java.lang.String[] { "RoleInfoType", "Money", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.RoleInfoSelectResponse.Builder.class);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_SCRolePoint_descriptor,
              new java.lang.String[] { "Point", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.Role.SCRolePoint.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.owlofwar_server_simplify_protobuf.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
