// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientGMMessage.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol.gm;

public final class ClientGMMessage {
  private ClientGMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CSGMMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use CSGMMessage.newBuilder() to construct.
    private CSGMMessage() {
      initFields();
    }
    private CSGMMessage(boolean noInit) {}
    
    private static final CSGMMessage defaultInstance;
    public static CSGMMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSGMMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_fieldAccessorTable;
    }
    
    // optional int32 type = 1 [default = 1];
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private int type_ = 1;
    public boolean hasType() { return hasType; }
    public int getType() { return type_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmRejectLoginRequest gmRejectLoginRequest = 2;
    public static final int GMREJECTLOGINREQUEST_FIELD_NUMBER = 2;
    private boolean hasGmRejectLoginRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest gmRejectLoginRequest_;
    public boolean hasGmRejectLoginRequest() { return hasGmRejectLoginRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest getGmRejectLoginRequest() { return gmRejectLoginRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmOpenLoginRequest gmOpenLoginRequest = 3;
    public static final int GMOPENLOGINREQUEST_FIELD_NUMBER = 3;
    private boolean hasGmOpenLoginRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest gmOpenLoginRequest_;
    public boolean hasGmOpenLoginRequest() { return hasGmOpenLoginRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest getGmOpenLoginRequest() { return gmOpenLoginRequest_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmTerminatedServerRequest gmTerminatedServerRequest = 4;
    public static final int GMTERMINATEDSERVERREQUEST_FIELD_NUMBER = 4;
    private boolean hasGmTerminatedServerRequest;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest gmTerminatedServerRequest_;
    public boolean hasGmTerminatedServerRequest() { return hasGmTerminatedServerRequest; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest getGmTerminatedServerRequest() { return gmTerminatedServerRequest_; }
    
    private void initFields() {
      gmRejectLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.getDefaultInstance();
      gmOpenLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.getDefaultInstance();
      gmTerminatedServerRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeInt32(1, getType());
      }
      if (hasGmRejectLoginRequest()) {
        output.writeMessage(2, getGmRejectLoginRequest());
      }
      if (hasGmOpenLoginRequest()) {
        output.writeMessage(3, getGmOpenLoginRequest());
      }
      if (hasGmTerminatedServerRequest()) {
        output.writeMessage(4, getGmTerminatedServerRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getType());
      }
      if (hasGmRejectLoginRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGmRejectLoginRequest());
      }
      if (hasGmOpenLoginRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGmOpenLoginRequest());
      }
      if (hasGmTerminatedServerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGmTerminatedServerRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasGmRejectLoginRequest()) {
          mergeGmRejectLoginRequest(other.getGmRejectLoginRequest());
        }
        if (other.hasGmOpenLoginRequest()) {
          mergeGmOpenLoginRequest(other.getGmOpenLoginRequest());
        }
        if (other.hasGmTerminatedServerRequest()) {
          mergeGmTerminatedServerRequest(other.getGmTerminatedServerRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setType(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.newBuilder();
              if (hasGmRejectLoginRequest()) {
                subBuilder.mergeFrom(getGmRejectLoginRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmRejectLoginRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.newBuilder();
              if (hasGmOpenLoginRequest()) {
                subBuilder.mergeFrom(getGmOpenLoginRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmOpenLoginRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.newBuilder();
              if (hasGmTerminatedServerRequest()) {
                subBuilder.mergeFrom(getGmTerminatedServerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmTerminatedServerRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 type = 1 [default = 1];
      public boolean hasType() {
        return result.hasType();
      }
      public int getType() {
        return result.getType();
      }
      public Builder setType(int value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = 1;
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmRejectLoginRequest gmRejectLoginRequest = 2;
      public boolean hasGmRejectLoginRequest() {
        return result.hasGmRejectLoginRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest getGmRejectLoginRequest() {
        return result.getGmRejectLoginRequest();
      }
      public Builder setGmRejectLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmRejectLoginRequest = true;
        result.gmRejectLoginRequest_ = value;
        return this;
      }
      public Builder setGmRejectLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.Builder builderForValue) {
        result.hasGmRejectLoginRequest = true;
        result.gmRejectLoginRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmRejectLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest value) {
        if (result.hasGmRejectLoginRequest() &&
            result.gmRejectLoginRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.getDefaultInstance()) {
          result.gmRejectLoginRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.newBuilder(result.gmRejectLoginRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmRejectLoginRequest_ = value;
        }
        result.hasGmRejectLoginRequest = true;
        return this;
      }
      public Builder clearGmRejectLoginRequest() {
        result.hasGmRejectLoginRequest = false;
        result.gmRejectLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmOpenLoginRequest gmOpenLoginRequest = 3;
      public boolean hasGmOpenLoginRequest() {
        return result.hasGmOpenLoginRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest getGmOpenLoginRequest() {
        return result.getGmOpenLoginRequest();
      }
      public Builder setGmOpenLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmOpenLoginRequest = true;
        result.gmOpenLoginRequest_ = value;
        return this;
      }
      public Builder setGmOpenLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.Builder builderForValue) {
        result.hasGmOpenLoginRequest = true;
        result.gmOpenLoginRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmOpenLoginRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest value) {
        if (result.hasGmOpenLoginRequest() &&
            result.gmOpenLoginRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.getDefaultInstance()) {
          result.gmOpenLoginRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.newBuilder(result.gmOpenLoginRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmOpenLoginRequest_ = value;
        }
        result.hasGmOpenLoginRequest = true;
        return this;
      }
      public Builder clearGmOpenLoginRequest() {
        result.hasGmOpenLoginRequest = false;
        result.gmOpenLoginRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmTerminatedServerRequest gmTerminatedServerRequest = 4;
      public boolean hasGmTerminatedServerRequest() {
        return result.hasGmTerminatedServerRequest();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest getGmTerminatedServerRequest() {
        return result.getGmTerminatedServerRequest();
      }
      public Builder setGmTerminatedServerRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmTerminatedServerRequest = true;
        result.gmTerminatedServerRequest_ = value;
        return this;
      }
      public Builder setGmTerminatedServerRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.Builder builderForValue) {
        result.hasGmTerminatedServerRequest = true;
        result.gmTerminatedServerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmTerminatedServerRequest(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest value) {
        if (result.hasGmTerminatedServerRequest() &&
            result.gmTerminatedServerRequest_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.getDefaultInstance()) {
          result.gmTerminatedServerRequest_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.newBuilder(result.gmTerminatedServerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmTerminatedServerRequest_ = value;
        }
        result.hasGmTerminatedServerRequest = true;
        return this;
      }
      public Builder clearGmTerminatedServerRequest() {
        result.hasGmTerminatedServerRequest = false;
        result.gmTerminatedServerRequest_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.CSGMMessage)
    }
    
    static {
      defaultInstance = new CSGMMessage(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.CSGMMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ClientGMMessage.proto\0229com.randioo.owl" +
      "ofwar_server_simplify_protobuf.protocol." +
      "gm\032\010GM.proto\"\361\002\n\013CSGMMessage\022\017\n\004type\030\001 \001" +
      "(\005:\0011\022m\n\024gmRejectLoginRequest\030\002 \001(\0132O.co" +
      "m.randioo.owlofwar_server_simplify_proto" +
      "buf.protocol.gm.GmRejectLoginRequest\022i\n\022" +
      "gmOpenLoginRequest\030\003 \001(\0132M.com.randioo.o" +
      "wlofwar_server_simplify_protobuf.protoco" +
      "l.gm.GmOpenLoginRequest\022w\n\031gmTerminatedS" +
      "erverRequest\030\004 \001(\0132T.com.randioo.owlofwa",
      "r_server_simplify_protobuf.protocol.gm.G" +
      "mTerminatedServerRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_CSGMMessage_descriptor,
              new java.lang.String[] { "Type", "GmRejectLoginRequest", "GmOpenLoginRequest", "GmTerminatedServerRequest", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ClientGMMessage.CSGMMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
