// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerGMMessage.proto

package com.randioo.owlofwar_server_simplify_protobuf.protocol.gm;

public final class ServerGMMessage {
  private ServerGMMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCGMMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use SCGMMessage.newBuilder() to construct.
    private SCGMMessage() {
      initFields();
    }
    private SCGMMessage(boolean noInit) {}
    
    private static final SCGMMessage defaultInstance;
    public static SCGMMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCGMMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmRejectLoginResponse gmRejectLoginResponse = 1;
    public static final int GMREJECTLOGINRESPONSE_FIELD_NUMBER = 1;
    private boolean hasGmRejectLoginResponse;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse gmRejectLoginResponse_;
    public boolean hasGmRejectLoginResponse() { return hasGmRejectLoginResponse; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse getGmRejectLoginResponse() { return gmRejectLoginResponse_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmOpenLoginResponse gmOpenLoginResponse = 2;
    public static final int GMOPENLOGINRESPONSE_FIELD_NUMBER = 2;
    private boolean hasGmOpenLoginResponse;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse gmOpenLoginResponse_;
    public boolean hasGmOpenLoginResponse() { return hasGmOpenLoginResponse; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse getGmOpenLoginResponse() { return gmOpenLoginResponse_; }
    
    // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmTerminatedServerResponse gmTerminatedServerResponse = 3;
    public static final int GMTERMINATEDSERVERRESPONSE_FIELD_NUMBER = 3;
    private boolean hasGmTerminatedServerResponse;
    private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse gmTerminatedServerResponse_;
    public boolean hasGmTerminatedServerResponse() { return hasGmTerminatedServerResponse; }
    public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse getGmTerminatedServerResponse() { return gmTerminatedServerResponse_; }
    
    private void initFields() {
      gmRejectLoginResponse_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.getDefaultInstance();
      gmOpenLoginResponse_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.getDefaultInstance();
      gmTerminatedServerResponse_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGmRejectLoginResponse()) {
        output.writeMessage(1, getGmRejectLoginResponse());
      }
      if (hasGmOpenLoginResponse()) {
        output.writeMessage(2, getGmOpenLoginResponse());
      }
      if (hasGmTerminatedServerResponse()) {
        output.writeMessage(3, getGmTerminatedServerResponse());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGmRejectLoginResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGmRejectLoginResponse());
      }
      if (hasGmOpenLoginResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGmOpenLoginResponse());
      }
      if (hasGmTerminatedServerResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGmTerminatedServerResponse());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage result;
      
      // Construct using com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage();
        return builder;
      }
      
      protected com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage.getDescriptor();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage getDefaultInstanceForType() {
        return com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage) {
          return mergeFrom((com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage other) {
        if (other == com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage.getDefaultInstance()) return this;
        if (other.hasGmRejectLoginResponse()) {
          mergeGmRejectLoginResponse(other.getGmRejectLoginResponse());
        }
        if (other.hasGmOpenLoginResponse()) {
          mergeGmOpenLoginResponse(other.getGmOpenLoginResponse());
        }
        if (other.hasGmTerminatedServerResponse()) {
          mergeGmTerminatedServerResponse(other.getGmTerminatedServerResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.newBuilder();
              if (hasGmRejectLoginResponse()) {
                subBuilder.mergeFrom(getGmRejectLoginResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmRejectLoginResponse(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.newBuilder();
              if (hasGmOpenLoginResponse()) {
                subBuilder.mergeFrom(getGmOpenLoginResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmOpenLoginResponse(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.Builder subBuilder = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.newBuilder();
              if (hasGmTerminatedServerResponse()) {
                subBuilder.mergeFrom(getGmTerminatedServerResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmTerminatedServerResponse(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmRejectLoginResponse gmRejectLoginResponse = 1;
      public boolean hasGmRejectLoginResponse() {
        return result.hasGmRejectLoginResponse();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse getGmRejectLoginResponse() {
        return result.getGmRejectLoginResponse();
      }
      public Builder setGmRejectLoginResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmRejectLoginResponse = true;
        result.gmRejectLoginResponse_ = value;
        return this;
      }
      public Builder setGmRejectLoginResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.Builder builderForValue) {
        result.hasGmRejectLoginResponse = true;
        result.gmRejectLoginResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmRejectLoginResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse value) {
        if (result.hasGmRejectLoginResponse() &&
            result.gmRejectLoginResponse_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.getDefaultInstance()) {
          result.gmRejectLoginResponse_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.newBuilder(result.gmRejectLoginResponse_).mergeFrom(value).buildPartial();
        } else {
          result.gmRejectLoginResponse_ = value;
        }
        result.hasGmRejectLoginResponse = true;
        return this;
      }
      public Builder clearGmRejectLoginResponse() {
        result.hasGmRejectLoginResponse = false;
        result.gmRejectLoginResponse_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmRejectLoginResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmOpenLoginResponse gmOpenLoginResponse = 2;
      public boolean hasGmOpenLoginResponse() {
        return result.hasGmOpenLoginResponse();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse getGmOpenLoginResponse() {
        return result.getGmOpenLoginResponse();
      }
      public Builder setGmOpenLoginResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmOpenLoginResponse = true;
        result.gmOpenLoginResponse_ = value;
        return this;
      }
      public Builder setGmOpenLoginResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.Builder builderForValue) {
        result.hasGmOpenLoginResponse = true;
        result.gmOpenLoginResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmOpenLoginResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse value) {
        if (result.hasGmOpenLoginResponse() &&
            result.gmOpenLoginResponse_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.getDefaultInstance()) {
          result.gmOpenLoginResponse_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.newBuilder(result.gmOpenLoginResponse_).mergeFrom(value).buildPartial();
        } else {
          result.gmOpenLoginResponse_ = value;
        }
        result.hasGmOpenLoginResponse = true;
        return this;
      }
      public Builder clearGmOpenLoginResponse() {
        result.hasGmOpenLoginResponse = false;
        result.gmOpenLoginResponse_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmOpenLoginResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GmTerminatedServerResponse gmTerminatedServerResponse = 3;
      public boolean hasGmTerminatedServerResponse() {
        return result.hasGmTerminatedServerResponse();
      }
      public com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse getGmTerminatedServerResponse() {
        return result.getGmTerminatedServerResponse();
      }
      public Builder setGmTerminatedServerResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmTerminatedServerResponse = true;
        result.gmTerminatedServerResponse_ = value;
        return this;
      }
      public Builder setGmTerminatedServerResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.Builder builderForValue) {
        result.hasGmTerminatedServerResponse = true;
        result.gmTerminatedServerResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmTerminatedServerResponse(com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse value) {
        if (result.hasGmTerminatedServerResponse() &&
            result.gmTerminatedServerResponse_ != com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.getDefaultInstance()) {
          result.gmTerminatedServerResponse_ =
            com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.newBuilder(result.gmTerminatedServerResponse_).mergeFrom(value).buildPartial();
        } else {
          result.gmTerminatedServerResponse_ = value;
        }
        result.hasGmTerminatedServerResponse = true;
        return this;
      }
      public Builder clearGmTerminatedServerResponse() {
        result.hasGmTerminatedServerResponse = false;
        result.gmTerminatedServerResponse_ = com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.GmTerminatedServerResponse.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.SCGMMessage)
    }
    
    static {
      defaultInstance = new SCGMMessage(true);
      com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.SCGMMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ServerGMMessage.proto\0229com.randioo.owl" +
      "ofwar_server_simplify_protobuf.protocol." +
      "gm\032\010GM.proto\"\346\002\n\013SCGMMessage\022o\n\025gmReject" +
      "LoginResponse\030\001 \001(\0132P.com.randioo.owlofw" +
      "ar_server_simplify_protobuf.protocol.gm." +
      "GmRejectLoginResponse\022k\n\023gmOpenLoginResp" +
      "onse\030\002 \001(\0132N.com.randioo.owlofwar_server" +
      "_simplify_protobuf.protocol.gm.GmOpenLog" +
      "inResponse\022y\n\032gmTerminatedServerResponse" +
      "\030\003 \001(\0132U.com.randioo.owlofwar_server_sim",
      "plify_protobuf.protocol.gm.GmTerminatedS" +
      "erverResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_owlofwar_server_simplify_protobuf_protocol_gm_SCGMMessage_descriptor,
              new java.lang.String[] { "GmRejectLoginResponse", "GmOpenLoginResponse", "GmTerminatedServerResponse", },
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage.class,
              com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.ServerGMMessage.SCGMMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.owlofwar_server_simplify_protobuf.protocol.gm.GM.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
